# Site settings
title: Tristan Rudolph
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tristan Rudolph
user_description: I'm a producer and multi-instrumentalist who feels most at home working with guitar driven pop music. I'm proficient in most major DAWs as well as the Waves plugin suite, Melodyne, and Ozone. My preferred MO is to record decisively and mix thoughtfully. 
user_title: Audio Engineer
email: tristanrudolph@protonmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
